### PR TITLE
User Requested Features/Fixes

### PR DESCRIPTION
**Pull request by EddieDover**
Pulls issues from #28 and #27 

- [x] Add secondary confirmation when deleting achievements.
- [x] Add the unlock\lock achievement button for all players. Of course, it also needs a second confirmation.
- [x] Compatible with Minimal-UI, make the UI smaller.
- [x] Can expand/collapse achievements.
- [x] Add lock achievement button to make it uneditable and smaller.
- [x] Adding a button to minimize the achivements list maybe to just the title would be nice

This PR does the following:
1. Adds the ability to lock achievements from being edited or deleted:
Foundry_Virtual_Tabletop_TjLDhvxjVO
2. Adds a confirmation dialog when deleting achievements.
Foundry_Virtual_Tabletop_SLeGtqITkU
3. Adds a 'Compact View' that hides the description and images on the achievement list.
Foundry_Virtual_Tabletop_vd2TpAZB0J
4. Fixed a class assignment issue with the icon, so it should also work with Minimal-UI now:
image

### CODE REVIEW

**Comment by TOUHOUCON** [comment]
You work really fast! I understand the complex design behind the drag and drop feature. Please do it at your pace.

I see the gif. Maybe put the edit and delete buttons next to the lock and keep just the icons. Probably like this:
287445793-7ac1447d-9eed-49d3-a19b-585243071e20

**Comment by EddieDover** [comment]
Foundry_Virtual_Tabletop_RsjXKWEAiK

@TOUHOUCON How's this look?

**Comment by TOUHOUCON** [comment]
@EddieDover It looks great! Might need some input from other users. 

However, the "compact view" doesn't seem to be aligned with the grid in front of it. Sorry I always notice small details.

**Comment by EddieDover** [comment]
Easy enough to fix. Thanks for pointing it out.
image

**Comment by EddieDover** [comment]
@TOUHOUCON Would you be willing to beta-test this release for me? I had to entirely rework a few things to get the mass-award/unaward working and I'd love a second set of eyes before this goes anywhere near the main branch.

**Comment by TOUHOUCON** [comment]
@EddieDover Sure! I will test it as soon as I can. 2 days is more than enough.

**Comment by EddieDover** [comment]
@TOUHOUCON fixed. Here's the new release:

[fvtt-player-achievements.zip](https://github.com/EddieDover/fvtt-player-achievements/files/13542135/fvtt-player-achievements.zip)

**Comment by TOUHOUCON** [comment]
DM has no bugs, I'm happy using it. But the character names seem to lean down a bit.
PLname

PL has a bug with player names being too long causing overflow.
BUG2

No more bugs.

**Comment by EddieDover** [comment]
> No more bugs.

Here's the latest release with those bugs hopefully fixed.

[fvtt-player-achievements.zip](https://github.com/EddieDover/fvtt-player-achievements/files/13543400/fvtt-player-achievements.zip)

**Comment by TOUHOUCON** [comment]
Still no alignment. I think this is kind of a minor issue.



PL view, long names will still overflow. But the DM view doesn't.

**Comment by EddieDover** [comment]
I must have uploaded the wrong version. I'm so sorry! 🙏🙏🙏
It's 00:30 so I'm sleepy ^^

Try this build:
[fvtt-player-achievements.zip](https://github.com/EddieDover/fvtt-player-achievements/files/13543682/fvtt-player-achievements.zip)

**Pull request merged**
